identity:
  service:
    base-url: http://localhost:8080

server:
  port: 8081

#Windows (PowerShell) - setx AUTH_JWT_SECRET "a-very-long-random-secret-at-least-32-characters"
#macOS/Linux - setx AUTH_JWT_SECRET "a-very-long-random-secret-at-least-32-characters"
auth:
  jwt:
    issuer: auth-service
    secret: ${AUTH_JWT_SECRET}
    expiration-minutes: 15

logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss.SSS}
      level=%-5level
      service=%X{service}
      traceId=%X{traceId}
      path=%X{path}
      durationMs=%X{durationMs}
      logger=%logger
      message="%msg"%n